src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     */
    private $publish_date;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/Hub/PostType.php
<?php

namespace App\Form\Hub;

use DateTime;
use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\Length;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'attr' => [
                    'maxlength' => 50,
                    'placeholder' => 'Post title',
                ],
                'constraints' => [
                    new Length([
                        'max' => 50
                    ])
                ]
            ])
            ->add('content', TextareaType::class, [
                'attr' => [
                    'maxlength' => 1000,
                ],
                'data' => "What's on your mind?",
                'constraints' => [
                    new Length([
                        'max' => 1000
                    ])
                ]
            ])
            ->add('publish_date', TextType::class, [
                'empty_data' => (new \DateTime())->format('YYYY-mm-dd'),
                'data'       => (new \DateTime())->format('d/m/Y'),
                'attr'       => [
                    'class' => 'datepicker',
                ],
            ])
            ->add('location', TextType::class, [
                'attr' => [
                    'maxlength' => 50,
                    'placeholder' => 'Where was it?',
                ],
                'required'  => false,
                'constraints' => [
                    new Length([
                        'max' => 50
                    ])
                ]
            ])
            ->add('picture', FileType::class, [
                'required'   => false,
            ])
        ;

        $builder->get('publish_date')->addModelTransformer(new CallbackTransformer(
            function($value) { return $value; },
            function($value) {
                $dt = DateTime::createFromFormat('d/m/Y', $value);

                return $dt;
            },
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/HubController.php
<?php

namespace App\Controller;

use App\Form\Hub\PostType;
use App\Manager\PostManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class HubController extends AbstractController
{
    /**
     * @Route("/hub", name="hub")
     */
    public function index(Request $request, PostManager $manager, Security $security)
    {
        $user    = $security->getUser();
        $newPost = $this->createForm(PostType::class);

        $newPost->handleRequest($request);

        if (!$newPost->isSubmitted()) {
            return $this->render('hub/index.html.twig', [
                'form'  => $newPost->createView(),
                'posts' => $user->getPosts(),
            ]);
        }

        $session = $request->getSession();

        if ($newPost->isValid()) {
            $post = $newPost->getData();

            $post->setUser($user);

            // This is ugly but temporary, do a proper Form type for that.
            $notify = $request->request->get('_notify', 'off');

            $manager->save($post, [
                'notify' => ($notify === 'on')
            ]);

            $session->getFlashBag()->add('success', 'Post published.');

            // Return to GET
            return $this->redirectToRoute('hub');
        }

        $session->getFlashBag()->add('error', 'Failed to publish post.');

        return $this->render('hub/index.html.twig', [
            'form'  => $newPost->createView(),
            'posts' => $user->getPosts(),
        ]);
    }
}

templates/hub/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Hub' %}

{% block body %}
    <div class="row">
        <header class="col-12">
            <h1 class="page-title"><i class="fab fa-hubspot"></i>&nbsp;{{ app.user.firstName }}'s hub</h1>
        </header>
        <aside class="col-xs-12 col-4">
            <h2 class="h4">Post something</h2>
            {{ form_start(form) }}
                <div class="form-group">
                    {{ form_widget(form.title)}}
                </div>
                <div class="form-group">
                    {{ form_widget(form.content)}}
                </div>
                <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                        </div>
                        {{ form_widget(form.publish_date)}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                        </div>
                        {{ form_widget(form.location)}}
                    </div>
                </div>
                <div class="form-group">
                    {{ form_widget(form.picture)}}
                </div>
                <div class="form-group">
                    <strong class="switch-label">Send notification</strong>
                    <label class="switch ">
                        <input name="_notify" type="checkbox" class="primary" checked>
                        <span class="slider"></span>
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary form-control btn-sm" value="Publish"/>
                </div>
            {{ form_end(form) }}
        </aside>
        <section class="col-xs-12 col-8">
            <article class="row">
                {% for post in posts %}
                    <div class="card col-12">
                        <div class="row no-gutters">
                            <div class="col-md-2">
                                <h5></h5>
                                <img src="{{ app.user.photo|default(constant('App\\Entity\\User::DEFAULT_PROFILE_PHOTO')) }}" class="card-img" />
                            </div>
                            <div class="col-md-10">
                                <div class="card-body">
                                    <h5 class="card-title">{{ post.title }}</h5>
                                    <p class="card-text">{{ post.content }}</p>
                                    <p class="card-text">
                                        <small class="text-muted">{{ post.user.firstname }}, {{ post.publishDate|date("d/m/Y") }}</small>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}

                {% endfor %}
            </article>
        </section>
    </div>
{% endblock %}